### ISSUE TITLE
PDF Form Formatting went missing after fill

### ISSUE THREAD

**Issue by macgoofy** [jay763190097/fill-pdf-utf8#2]
Is there a way to avoid removing the defined format-options e.g. from textboxes such as font-size and background-color?
Somehow they went missing after using fill-pdf-utf8 and generatePdf-method

For testing:
Use/Create a Source-PDF with formatted textfield (like white background and font-size to 20).
Look into the Destionation-PDF and see that there's missing the white background

**Comment by jay763190097** [comment]
if you want to edit the PDF file, you can edit index.js and delete the parameter '-','flatten',
